-- AlterTable
ALTER TABLE `IssuedCertificate` ADD COLUMN `fileData` LONGBLOB NULL,
    ADD COLUMN `fileMimeType` VARCHAR(191) NULL,
    ADD COLUMN `fileName` VARCHAR(191) NULL,
    ADD COLUMN `fileSize` INTEGER NULL,
    ADD COLUMN `reminderSentAt` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('PENDING_UPLOAD', 'UPLOADED') NOT NULL DEFAULT 'PENDING_UPLOAD',
    ADD COLUMN `uploadedAt` DATETIME(3) NULL,
    ADD COLUMN `uploadedBy` VARCHAR(191) NULL;
